#baseURL = 'http://example.org/'
languageCode = "zh-CN"
title = 'LoveGlazeçš„åšå®¢'
theme = "kagome"
math = true
#ä¸»é¡µæŒ‰é’®
[[menu.main]]
    identifier = 'home'
    name = 'ğŸ ä¸»é¡µ'
    title = 'home'
    url = '/'
    weight = 10
#å½’æ¡£æŒ‰é’®
[[menu.main]]
    identifier = 'posts'
    name = 'ğŸ¨ çµå¢ƒ'
    title = 'posts' 
    url = '/posts/'
    weight = 20
#å½’æ¡£æŒ‰é’®
[[menu.main]]
    identifier = 'soul'
    name = 'ğŸ¼ ç¢å¿µ'
    title = 'soul' 
    url = '/soul/'
    weight = 30
#å…³äºæŒ‰é’®
[[menu.main]]
    identifier = 'about'
    name = 'ğŸ˜ˆ å…³äº'
    title = 'about' 
    url = '/about/'
    weight = 40
    #å‹é“¾æŒ‰é’®
[[menu.main]]
    identifier = 'link'
    name = 'ğŸ”— LINK'
    title = 'å‹é“¾' 
    url = '/link'
    weight = 50

#ç¤¾äº¤èœå•
[[menu.social]]
    # å”¯ä¸€æ ‡è¯†ç¬¦
    identifier = "github"
    # åç§°
    name = "github"
    # urlåœ°å€
    url = "https://github.com/LoveGlaze"
    # æƒé‡ è¶Šå°è¶Šé å‰
    weight = 1
[[menu.social]]
    # å”¯ä¸€æ ‡è¯†ç¬¦
    identifier = "twitter"
    # åç§°
    name = "Twitter"
    # urlåœ°å€
    url = "https://twitter.com/LoveGlazeK"
    # æƒé‡ è¶Šå°è¶Šé å‰
    weight = 2
[[menu.social]]
    # å”¯ä¸€æ ‡è¯†ç¬¦
    identifier = "instagram"
    # åç§°
    name = "instagram"
    # urlåœ°å€
    url = "https://www.instagram.com/yokeagoni/"
    # æƒé‡ è¶Šå°è¶Šé å‰
    weight = 3

[author]
    name = "LoveGlaze"
    email = "617683180@qq.com"
    description = "å¹´è½»ä¸”ä¼˜ç§€ï¼Œç§¯æä¸”é¢“åºŸ"
    avatar = "/images/head.jpg"

##params å­—æ®µçš„å†…å®¹å¯ä¾›ä¸»é¢˜æ¨¡æ¿è¯»å–
[params]
    beian='æ»‡ICPå¤‡2021002928å·-1'
    mainSections='posts,soul'
[params.aplayer]
    autoplay=false

##ä»£ç é«˜äº®
[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        noClasses = true
        style = "dracula"
        tabWidth = 4
[markup.goldmark.renderer]
unsafe= true


